"use client";
import Map from "@/components/Map";
import { useEffect, useState } from "react";
import Papa from "papaparse";

export default function Home() {
  const [data, setData] = useState([]);
   const options = [
    {value: "Select All", label: "Select All"},
    {value: "0100", label: "Suspect Impersonate"},
    {value: "0101", label: "Aid victim"},
    {value: "0102", label: "Blind"},
    {value: "0103", label: "Crippled"},
    {value: "0104", label: "Customer"},
    {value: "0105", label: "Delivery"},
    {value: "0106", label: "Doctor"},
    {value: "0107", label: "God"},
    {value: "0108", label: "Infirm"},
    {value: "0109", label: "Inspector"},
    {value: "0110", label: "Involved in traffic/accident"},
    {value: "0112", label: "Police"},
    {value: "0113", label: "Renting"},
    {value: "0114", label: "Repair Person"},
    {value: "0115", label: "Returning stolen property"},
    {value: "0116", label: "Satan"},
    {value: "0117", label: "Salesman"},
    {value: "0118", label: "Seeking someone"},
    {value: "0119", label: "Sent by owner"},
    {value: "0120", label: "Social Security/Medicare"},
    {value: "0121", label: "DWP/Gas Company/Utility worker"},
    {value: "0122", label: "Contractor"},
    {value: "0123", label: "Gardener/Tree Trimmer"},
    {value: "0200", label: "Suspect wore disguise"},
    {value: "0201", label: "Bag"},
    {value: "0202", label: "Cap/hat"},
    {value: "0203", label: "Cloth (with eyeholes)"},
    {value: "0204", label: "Clothes of opposite sex"},
    {value: "0205", label: "Earring"},
    {value: "0206", label: "Gloves"},
    {value: "0207", label: "Handkerchief"},
    {value: "0208", label: "Halloween mask"},
    {value: "0209", label: "Mask"},
    {value: "0210", label: "Make up (males only)"},
    {value: "0211", label: "Shoes"},
    {value: "0212", label: "Nude/partly nude"},
    {value: "0213", label: "Ski mask"},
    {value: "0214", label: "Stocking"},
    {value: "0215", label: "Unusual clothes"},
    {value: "0216", label: "Suspect wore hood/hoodie"},
    {value: "0217", label: "Uniform"},
    {value: "0218", label: "Wig"},
    {value: "0219", label: "Mustache-Fake"},
    {value: "0220", label: "Suspect wore motorcycle helmet"},
    {value: "0301", label: "Escaped on (used) transit train"},
    {value: "0302", label: "Aimed gun"},
    {value: "0303", label: "Ambushed"},
    {value: "0304", label: "Ate/drank on premises"},
    {value: "0305", label: "Attacks from rear"},
    {value: "0306", label: "Crime on upper floor"},
    {value: "0307", label: "Defecated/urinated"},
    {value: "0308", label: "Demands jewelry"},
    {value: "0309", label: "Drive-by shooting"},
    {value: "0310", label: "Got victim to withdraw savings"},
    {value: "0311", label: "Graffiti"},
    {value: "0312", label: "Gun in waistband"},
    {value: "0313", label: "Hid in building"},
    {value: "0314", label: "Hot Prowl"},
    {value: "0315", label: "Jumped counter/goes behind counter"},
    {value: "0316", label: "Makes victim give money"},
    {value: "0317", label: "Pillowcase/suitcase"},
    {value: "0318", label: "Prepared exit"},
    {value: "0319", label: "Profanity Used"},
    {value: "0320", label: "Quiet polite"},
    {value: "0321", label: "Ransacked"},
    {value: "0322", label: "Smashed display case"},
    {value: "0323", label: "Smoked on premises"},
    {value: "0324", label: "Takes money from register"},
    {value: "0325", label: "Took merchandise"},
    {value: "0326", label: "Used driver"},
    {value: "0327", label: "Used lookout"},
    {value: "0328", label: "Used toilet"},
    {value: "0329", label: "Vandalized"},
    {value: "0330", label: "Victims vehicle taken"},
    {value: "0331", label: "Mailbox Bombing"},
    {value: "0332", label: "Mailbox Vandalism"},
    {value: "0333", label: "Used hand held radios"},
    {value: "0334", label: "Brandishes weapon"},
    {value: "0335", label: "Cases location"},
    {value: "0336", label: "Chain snatch"},
    {value: "0337", label: "Demands money"},
    {value: "0338", label: "Disables Telephone"},
    {value: "0339", label: "Disables video camera"},
    {value: "0340", label: "Suspect follows victim/follows victim home"},
    {value: "0341", label: "Makes vict lie down"},
    {value: "0342", label: "Multi-susps overwhelm"},
    {value: "0343", label: "Orders vict to rear room"},
    {value: "0344", label: "Removes vict property"},
    {value: "0345", label: "Riding bike"},
    {value: "0346", label: "Snatch property and runs"},
    {value: "0347", label: "Stalks vict"},
    {value: "0348", label: "Takeover other"},
    {value: "0349", label: "Takes mail"},
    {value: "0350", label: "Concealed victim's body"},
    {value: "0351", label: "Disabled Security"},
    {value: "0352", label: "Took Victim's clothing or jewelry"},
    {value: "0353", label: "Weapon Concealed"},
    {value: "0354", label: "Suspect takes car keys"},
    {value: "0355", label: "Demanded property other than money"},
    {value: "0356", label: "Suspect spits on victim"},
    {value: "0357", label: "Cuts or breaks purse strap"},
    {value: "0358", label: "Forces Entry"},
    {value: "0359", label: "Made unusual statement"},
    {value: "0360", label: "Suspect is Other Family Member"},
    {value: "0361", label: "Suspect is neighbor"},
    {value: "0362", label: "Suspect attempts to carry victim away"},
    {value: "0363", label: "Home invasion"},
    {value: "0364", label: "Suspect is babysitter"},
    {value: "0365", label: "Takeover robbery"},
    {value: "0366", label: "Ordered vict to open safe"},
    {value: "0367", label: "Was Transit Patrol"},
    {value: "0368", label: "Suspect speaks foreign language"},
    {value: "0369", label: "Suspect speaks spanish"},
    {value: "0370", label: "Frisks victim/pats down victim/searches victim"},
    {value: "0371", label: "Gang affiliation questions asked/made gang statement"},
    {value: "0372", label: "Photographed victim/took pictures of victim"},
    {value: "0373", label: "Handicapped/in wheelchair"},
    {value: "0374", label: "Gang signs/threw gang signs using hands"},
    {value: "0375", label: "Removes cash register"},
    {value: "0376", label: "Makes victim kneel"},
    {value: "0377", label: "Takes vict's identification/driver license"},
    {value: "0378", label: "Brings own bag"},
    {value: "0379", label: "Turns off lights/electricity"},
    {value: "0380", label: "Distracts Victim"},
    {value: "0381", label: "Suspect apologizes"},
    {value: "0382", label: "Removed money/property from safe"},
    {value: "0383", label: "Suspect entered during open house/party/estate/yard sale"},
    {value: "0384", label: "Suspect removed drugs from location"},
    {value: "0385", label: "Suspect removed parts from vehicle"},
    {value: "0386", label: "Suspect removed property from trunk of vehicle"},
    {value: "0387", label: "Weapon (other than gun) in waistband"},
    {value: "0388", label: "Suspect points laser at plane/helicopter"},
    {value: "0389", label: "Knock-knock"},
    {value: "0390", label: "Purse snatch"},
    {value: "0391", label: "Used demand note"},
    {value: "0392", label: "False Emergency Reporting"},
    {value: "0393", label: "911 Abuse"},
    {value: "0394", label: "Susp takes UPS, Fedex, USPS packages"},
    {value: "0395", label: "Murder/Suicide"},
    {value: "0396", label: "Used paper plates to disguise license number"},
    {value: "0397", label: "Cut lock (to bicycle, gate, etc."},
    {value: "0398", label: "Roof access (remove A/C, equip, etc.)"},
    {value: "0399", label: "Vehicle to Vehicle shooting"},
    {value: "0400", label: "Force used"},
    {value: "0401", label: "Bit"},
    {value: "0402", label: "Blindfolded"},
    {value: "0403", label: "Bomb Threat, Bomb found"},
    {value: "0404", label: "Bomb Threat, no bomb"},
    {value: "0405", label: "Bound"},
    {value: "0406", label: "Brutal Assault"},
    {value: "0407", label: "Burned Victim"},
    {value: "0408", label: "Choked/uses choke hold/Strangulation/Suffocation"},
    {value: "0409", label: "Cover mouth w/hands"},
    {value: "0410", label: "Covered victim's face"},
    {value: "0411", label: "Cut/stabbed"},
    {value: "0412", label: "Disfigured"},
    {value: "0413", label: "Drugged"},
    {value: "0414", label: "Gagged"},
    {value: "0415", label: "Handcuffed/Metal"},
    {value: "0416", label: "Hit-Hit w/ weapon"},
    {value: "0417", label: "Kicked"},
    {value: "0418", label: "Kidnapped"},
    {value: "0419", label: "Pulled victims hair"},
    {value: "0420", label: "Searched"},
    {value: "0421", label: "Threaten to kill"},
    {value: "0422", label: "Threaten Victims family"},
    {value: "0423", label: "Tied victim to object"},
    {value: "0424", label: "Tore clothes off victim"},
    {value: "0425", label: "Tortured"},
    {value: "0426", label: "Twisted arm"},
    {value: "0427", label: "Whipped"},
    {value: "0428", label: "Dismembered"},
    {value: "0429", label: "Vict knocked to ground"},
    {value: "0430", label: "Vict shot"},
    {value: "0431", label: "Sprayed with chemical"},
    {value: "0432", label: "Intimidation"},
    {value: "0433", label: "Makes victim kneel"},
    {value: "0434", label: "Bed Sheets/Linens"},
    {value: "0435", label: "Chain"},
    {value: "0436", label: "Clothing"},
    {value: "0437", label: "Flexcuffs/Plastic Tie"},
    {value: "0438", label: "Rope/Cordage"},
    {value: "0439", label: "Tape/Electrical etc..."},
    {value: "0440", label: "Telephone/Electric Cord"},
    {value: "0441", label: "Wire"},
    {value: "0442", label: "Active Shooter/Armed person who has used deadly physical force on other persons & aggressively continues while having access to more victim's"},
    {value: "0443", label: "Threaten to harm victim (other than kill)"},
    {value: "0444", label: "Pushed"},
    {value: "0445", label: "Suspect swung weapon"},
    {value: "0446", label: "Suspect swung fist"},
    {value: "0447", label: "Suspect threw object at victim"},
    {value: "0448", label: "Grabbed"},
    {value: "0449", label: "Put a weapon to body"},
    {value: "0450", label: "Suspect shot at victim (no hits)"},
    {value: "0500", label: "Sex related acts"},
    {value: "0501", label: "Susp ejaculated outside victim"},
    {value: "0502", label: "Fecal Fetish"},
    {value: "0503", label: "Fondle victim"},
    {value: "0504", label: "Forced to disrobe"},
    {value: "0505", label: "Forced to fondle suspect"},
    {value: "0506", label: "Forced to masturbate suspect"},
    {value: "0507", label: "Forced to orally copulate suspect"},
    {value: "0508", label: "Hit victim prior, during, after act"},
    {value: "0509", label: "Hugged"},
    {value: "0510", label: "Kissed victims body/face"},
    {value: "0511", label: "Masochism/bondage"},
    {value: "0512", label: "Orally copulated victim"},
    {value: "0513", label: "Photographed victim"},
    {value: "0514", label: "Pornography"},
    {value: "0515", label: "Put hand, finger or object into vagina"},
    {value: "0516", label: "Reached climax/ejaculated"},
    {value: "0517", label: "Sadism/Sexual gratification obtained by infliction of physical or mental pain on others"},
    {value: "0518", label: "Simulated intercourse"},
    {value: "0519", label: "Sodomy"},
    {value: "0520", label: "Solicited/offered immoral act"},
    {value: "0521", label: "Tongue or mouth to anus"},
    {value: "0522", label: "Touched"},
    {value: "0523", label: "Unable to get erection"},
    {value: "0524", label: "Underwear Fetish"},
    {value: "0525", label: "Urinated"},
    {value: "0526", label: "Utilized Condom"},
    {value: "0527", label: "Actual Intercourse"},
    {value: "0528", label: "Masturbate"},
    {value: "0529", label: "Indecent Exposure"},
    {value: "0530", label: "Used lubricant"},
    {value: "0531", label: "Suspect made sexually suggestive remarks"},
    {value: "0532", label: "Suspect undressed victim"},
    {value: "0533", label: "Consentual Sex"},
    {value: "0534", label: "Suspect in vehicle nude/partially nude"},
    {value: "0535", label: "Suspect asks minor's name"},
    {value: "0536", label: "Suspect removes own clothing"},
    {value: "0537", label: "Suspect removes victim's clothing"},
    {value: "0538", label: "Suspect fondles self"},
    {value: "0539", label: "Suspect puts hand in victim's rectum"},
    {value: "0540", label: "Suspect puts finger(s) in victim's rectum"},
    {value: "0541", label: "Suspect puts object(s) in victim's rectum"},
    {value: "0542", label: "Orders victim to undress"},
    {value: "0543", label: "Orders victim to fondle suspect"},
    {value: "0544", label: "Orders victim to fondle self"},
    {value: "0545", label: "Male Victim of sexual assault"},
    {value: "0546", label: "Susp instructs vict to make certain statements"},
    {value: "0547", label: "Suspect force vict to bathe/clean/wipe"},
    {value: "0548", label: "Suspect gives victim douche/enema"},
    {value: "0549", label: "Suspect ejaculates in victims mouth"},
    {value: "0550", label: "Suspect licks victim"},
    {value: "0551", label: "Suspect touches victim genitalia/genitals over clothing"},
    {value: "0552", label: "Suspect is Victim's Father"},
    {value: "0553", label: "Suspect is Victim's Mother"},
    {value: "0554", label: "Suspect is Victim's Brother"},
    {value: "0555", label: "Suspect is Victim's Sister"},
    {value: "0556", label: "Suspect is Victim's Step-Father"},
    {value: "0557", label: "Suspect is Victim's Step-Mother"},
    {value: "0558", label: "Suspect is Victim's Uncle"},
    {value: "0559", label: "Suspect is Victim's Aunt"},
    {value: "0560", label: "Suspect is Victim's Guardian"},
    {value: "0561", label: "Suspect is Victim's Son"},
    {value: "0562", label: "Suspect is Victim's Daughter"},
    {value: "0563", label: "Fetish, Other"},
    {value: "0601", label: "Business"},
    {value: "0602", label: "Family"},
    {value: "0603", label: "Landlord/Tenant/Neighbor"},
    {value: "0604", label: "Reproductive Health Services/Facilities"},
    {value: "0605", label: "Traffic Accident/Traffic related incident"},
    {value: "0701", label: "THEFT: Trick or Device"},
    {value: "0800", label: "BUNCO"},
    {value: "0901", label: "Organized Crime"},
    {value: "0902", label: "Political Activity"},
    {value: "0903", label: "Hatred/Prejudice"},
    {value: "0904", label: "Strike/Labor Troubles"},
    {value: "0905", label: "Terrorist Group"},
    {value: "0906", label: "Gangs"},
    {value: "0907", label: "Narcotics (Buy-Sell-Rip)"},
    {value: "0908", label: "Prostitution"},
    {value: "0909", label: "Ritual/Occult"},
    {value: "0910", label: "Public Transit (Metrolink/Train Station,Metro Rail Red,Line Subway Station,"},
    {value: "Metro", label: "Rail Blue Line Station,adjacent transit parking lots, tracks or tunnels"},
    {value: "MTA(RTD),", label: "and other municipal lines."},
    {value: "0911", label: "Revenge"},
    {value: "0912", label: "Insurance"},
    {value: "0913", label: "Victim knew Suspect"},
    {value: "0914", label: "Other Felony"},
    {value: "0915", label: "Parolee"},
    {value: "0916", label: "Forced theft of vehicle (Car-Jacking)"},
    {value: "0917", label: "Victim's Employment"},
    {value: "0918", label: "Career Criminal"},
    {value: "0919", label: "Road Rage"},
    {value: "0920", label: "Homeland Security"},
    {value: "0921", label: "Hate Incident"},
    {value: "0922", label: "ATM Theft with PIN number"},
    {value: "0923", label: "Stolen/Forged Checks (Personal Checks)"},
    {value: "0924", label: "Stolen/Forged Checks (Business Checks)"},
    {value: "0925", label: "Stolen/Forged Checks (Cashier's Checks)"},
    {value: "0926", label: "Forged or Telephonic Prescription"},
    {value: "0927", label: "Fraudulent or forged school loan"},
    {value: "0928", label: "Forged or Fraudulent credit applications"},
    {value: "0929", label: "Unauthorized use of victim's bank account information"},
    {value: "0930", label: "Unauthorized use of victim's credit/debit card or number"},
    {value: "0931", label: "Counterfeit or forged real estate documents"},
    {value: "0932", label: "Suspect uses victim's identity in reporting a traffic collision"},
    {value: "0933", label: "Suspect uses victim's identity when arrested"},
    {value: "0934", label: "Suspect uses victim's identity when receiving a citation"},
    {value: "0935", label: "Misc. Stolen/Forged documents"},
    {value: "0936", label: "Dog Fighting"},
    {value: "0937", label: "Cock Fighting"},
    {value: "0938", label: "Animal Neglect"},
    {value: "0939", label: "Animal Hoarding"},
    {value: "0940", label: "Met online/Chat Room/on Party Line"},
    {value: "0941", label: "Non-Revocable Parole (NRP)"},
    {value: "0942", label: "Party/Flier party/Rave Party"},
    {value: "0943", label: "Human Trafficking"},
    {value: "0944", label: "Bait Operation"},
    {value: "0945", label: "Estes Robbery"},
    {value: "0946", label: "Gang Feud"},
    {value: "1000", label: "Suspects offers/solicits"},
    {value: "1001", label: "Aid for vehicle"},
    {value: "1002", label: "Amusement"},
    {value: "1003", label: "appraise"},
    {value: "1004", label: "Assistant"},
    {value: "1005", label: "Audition"},
    {value: "1006", label: "Bless"},
    {value: "1007", label: "Candy"},
    {value: "1008", label: "Cigarette"},
    {value: "1009", label: "Directions"},
    {value: "1010", label: "Drink (not liquor)"},
    {value: "1011", label: "Employment"},
    {value: "1012", label: "Find a job"},
    {value: "1013", label: "Food"},
    {value: "1014", label: "Game"},
    {value: "1015", label: "Gift"},
    {value: "1016", label: "Hold for safekeeping"},
    {value: "1017", label: "Information"},
    {value: "1018", label: "Liquor"},
    {value: "1019", label: "Money"},
    {value: "1020", label: "Narcotics"},
    {value: "1021", label: "Repair"},
    {value: "1022", label: "Ride"},
    {value: "1023", label: "Subscriptions"},
    {value: "1024", label: "Teach"},
    {value: "1025", label: "Train"},
    {value: "1026", label: "Use the phone or toilet"},
    {value: "1027", label: "Change"},
    {value: "1028", label: "Suspect solicits time of day"},
    {value: "1100", label: "Shots Fired"},
    {value: "1101", label: "Shots Fired (Animal) - Animal Services"},
    {value: "1201", label: "Absent-advertised in paper"},
    {value: "1202", label: "Aged (60 & over) or blind/crippled/unable to care for self"},
    {value: "1203", label: "Victim of crime past 12 months"},
    {value: "1204", label: "Moving"},
    {value: "1205", label: "On Vacation/Tourist"},
    {value: "1206", label: "Under influence drugs/liquor"},
    {value: "1207", label: "Hitchhiker"},
    {value: "1208", label: "Illegal Alien"},
    {value: "1209", label: "Salesman, Jewelry"},
    {value: "1210", label: "Professional (doctor, Lawyer, etc.)"},
    {value: "1211", label: "Public Official"},
    {value: "1212", label: "LA Police Officer"},
    {value: "1213", label: "LA Fireman"},
    {value: "1214", label: "Banking, ATM"},
    {value: "1215", label: "Prostitute"},
    {value: "1216", label: "Sales"},
    {value: "1217", label: "Teenager(Use if victim's age is unknown)"},
    {value: "1218", label: "Victim was Homeless/Transient"},
    {value: "1219", label: "Nude"},
    {value: "1220", label: "Partially Nude"},
    {value: "1221", label: "Missing Clothing/Jewelry"},
    {value: "1222", label: "Homosexual/Gay"},
    {value: "1223", label: "Riding bike"},
    {value: "1224", label: "Drive-through (not merchant)"},
    {value: "1225", label: "Stop sign/light"},
    {value: "1226", label: "Catering Truck Operator"},
    {value: "1227", label: "Delivery person"},
    {value: "1228", label: "Leaving Business Area"},
    {value: "1229", label: "Making bank drop"},
    {value: "1230", label: "Postal employee"},
    {value: "1231", label: "Taxi Driver"},
    {value: "1232", label: "Bank, Arriving at"},
    {value: "1233", label: "Bank, Leaving"},
    {value: "1234", label: "Bar Customer"},
    {value: "1235", label: "Bisexual/sexually oriented towards both sexes"},
    {value: "1236", label: "Clerk/Employer/Owner"},
    {value: "1237", label: "Customer"},
    {value: "1238", label: "Handicapped"},
    {value: "1239", label: "Transgender"},
    {value: "1240", label: "Vehicle occupant/Passenger"},
    {value: "1241", label: "Spouse"},
    {value: "1242", label: "Parent"},
    {value: "1243", label: "Co-habitants"},
    {value: "1244", label: "Victim was forced into business"},
    {value: "1245", label: "Victim was forced into residence"},
    {value: "1247", label: "Opening business"},
    {value: "1248", label: "Closing business"},
    {value: "1251", label: "Victim was a student"},
    {value: "1252", label: "Victim was a street vendor"},
    {value: "1253", label: "Bus Driver"},
    {value: "1254", label: "Train Operator"},
    {value: "1255", label: "Followed Transit System"},
    {value: "1256", label: "Patron"},
    {value: "1257", label: "Victim is Newborn-5 years old"},
    {value: "1258", label: "Victim is 6 years old thru 13 years old"},
    {value: "1259", label: "Victim is 14 years old thru 17 years old"},
    {value: "1260", label: "Deaf/Hearing Impaired"},
    {value: "1261", label: "Mentally Challenged/Retarded/Intellectually Slow"},
    {value: "1262", label: "Raped while unconscious"},
    {value: "1263", label: "Agricultural Target"},
    {value: "1264", label: "Pipeline"},
    {value: "1265", label: "Mailbox"},
    {value: "1266", label: "Victim was security guard"},
    {value: "1267", label: "Home under construction"},
    {value: "1268", label: "Victim was 5150/Mental Illness"},
    {value: "1269", label: "Victim was armored car driver"},
    {value: "1270", label: "Victim was gang member"},
    {value: "1271", label: "Victim was Law Enforcement (not LAPD)"},
    {value: "1272", label: "Victim was at/leaving medical/retail/non-retail cannabis location"},
    {value: "1273", label: "Home was being fumigated"},
    {value: "1274", label: "Victim was Inmate/Incarcerated"},
    {value: "1275", label: "Vacant Residence/Building"},
    {value: "1276", label: "Pregnant"},
    {value: "1277", label: "Gardner"},
    {value: "1278", label: "Victim was Uber/Lyft driver"},
    {value: "1279", label: "Victim was Foster child"},
    {value: "1280", label: "Victim was Foster parent"},
    {value: "1281", label: "Victim was Pistol-whipped"},
    {value: "1300", label: "Vehicle involved"},
    {value: "1301", label: "Forced victim vehicle to curb"},
    {value: "1302", label: "Suspect forced way into victim's vehicle"},
    {value: "1303", label: "Hid in rear seat"},
    {value: "1304", label: "Stopped victim vehicle by flagging down, forcing T/A, etc."},
    {value: "1305", label: "Victim forced into vehicle"},
    {value: "1306", label: "Victim parking, garaging vehicle"},
    {value: "1307", label: "Breaks window"},
    {value: "1308", label: "Drives by and snatches property"},
    {value: "1309", label: "Susp uses vehicle"},
    {value: "1310", label: "Victim in vehicle"},
    {value: "1311", label: "Victim removed from vehicle"},
    {value: "1312", label: "Suspect follows victim in vehicle"},
    {value: "1313", label: "Suspect exits vehicle and attacks pedestrian"},
    {value: "1314", label: "Victim loading vehicle"},
    {value: "1315", label: "Victim unloading vehicle"},
    {value: "1316", label: "Victim entering their vehicle"},
    {value: "1317", label: "Victim exiting their vehicle"},
    {value: "1318", label: "Suspect follows victim home"},
    {value: "1401", label: "Blood Stains"},
    {value: "1402", label: "Evidence Booked (any crime)"},
    {value: "1403", label: "Fingerprints"},
    {value: "1404", label: "Footprints"},
    {value: "1405", label: "Left Note"},
    {value: "1406", label: "Tool Marks"},
    {value: "1407", label: "Bullets/Casings"},
    {value: "1408", label: "Bite Marks"},
    {value: "1409", label: "Clothes"},
    {value: "1410", label: "Gun Shot Residue"},
    {value: "1411", label: "Hair"},
    {value: "1412", label: "Jewelry"},
    {value: "1413", label: "Paint"},
    {value: "1414", label: "Photographs"},
    {value: "1415", label: "Rape Kit"},
    {value: "1416", label: "Saliva"},
    {value: "1417", label: "Semen"},
    {value: "1418", label: "Skeleton/Bones"},
    {value: "1419", label: "Firearm booked as evidence"},
    {value: "1420", label: "Video surveillance booked/available"},
    {value: "1501", label: "Other MO (see rpt)"},
    {value: "1601", label: "Bodily Force"},
    {value: "1602", label: "Cutting Tool"},
    {value: "1603", label: "Knob Twist"},
    {value: "1604", label: "Lock Box"},
    {value: "1605", label: "Lock slip/key/pick"},
    {value: "1606", label: "Open/unlocked"},
    {value: "1607", label: "Pried"},
    {value: "1608", label: "Removed"},
    {value: "1609", label: "Smashed"},
    {value: "1610", label: "Tunneled"},
    {value: "1611", label: "Shaved Key"},
    {value: "1612", label: "Punched/Pulled Door Lock"},
    {value: "1701", label: "Elder Abuse/Physical"},
    {value: "1702", label: "Elder Abuse/Financial"},
    {value: "1801", label: "Susp is/was mother's boyfriend"},
    {value: "1802", label: "Susp is/was victim's co-worker"},
    {value: "1803", label: "Susp is/was victim's employee"},
    {value: "1804", label: "Susp is/was victim's employer"},
    {value: "1805", label: "Susp is/was fellow gang member"},
    {value: "1806", label: "Susp is/was father's girlfriend"},
    {value: "1807", label: "Susp is/was priest/pastor"},
    {value: "1808", label: "Susp is/was other religious confidant"},
    {value: "1809", label: "Susp is/was rival gang member"},
    {value: "1810", label: "Susp is/was roommate"},
    {value: "1811", label: "Susp is/was victim's teacher/coach"},
    {value: "1812", label: "Susp is/was foster parent/sibling"},
    {value: "1813", label: "Susp is/was current/former spouse/co-habitant"},
    {value: "1814", label: "Susp is/was current/former boyfriend/girlfriend"},
    {value: "1815", label: "Susp was student"},
    {value: "1816", label: "Suspect is/was known gang member"},
    {value: "1817", label: "Acquaintance"},
    {value: "1818", label: "Caretaker/care-giver/nanny"},
    {value: "1819", label: "Common-law Spouse"},
    {value: "1820", label: "Friend"},
    {value: "1821", label: "Spouse"},
    {value: "1822", label: "Stranger"},
    {value: "1823", label: "Brief encounter/Date"},
    {value: "1824", label: "Classmate"},
    {value: "1900", label: "Auction Fraud/eBay/cragslist,etc. (Internet based theft)"},
    {value: "1901", label: "Child Pornography/In possession of/Via computer"},
    {value: "1902", label: "Credit Card Fraud/Theft of services via internet"},
    {value: "1903", label: "Cyberstalking (Stalking using internet to commit the crime)"},
    {value: "1904", label: "Denial of computer services"},
    {value: "1905", label: "Destruction of computer data"},
    {value: "1906", label: "Harrassing E-Mail/Text Message/Other Electronic Communications"},
    {value: "1907", label: "Hate Crime materials/printouts/e-mails"},
    {value: "1908", label: "Identity Theft via computer"},
    {value: "1909", label: "Introduction of virus or contaminants into computer system/program"},
    {value: "1910", label: "Minor solicited for sex via internet/Known minor"},
    {value: "1911", label: "Theft of computer data"},
    {value: "1912", label: "Threatening E-mail/Text Messages"},
    {value: "1913", label: "Suspect meets victim on internet/chatroom"},
    {value: "1914", label: "Unauthorized access to computer system"},
    {value: "1915", label: "Internet Extortion"},
    {value: "1916", label: "Victim paid by wire transfer"},
    {value: "2000", label: "Domestic violence"},
    {value: "2001", label: "Suspect on drugs"},
    {value: "2002", label: "Suspect intoxicated/drunk"},
    {value: "2003", label: "Suspect 5150/mentally challenged or disturbed"},
    {value: "2004", label: "Suspect is homeless/transient"},
    {value: "2005", label: "Suspect uses wheelchair"},
    {value: "2006", label: "Suspect was transgender"},
    {value: "2007", label: "Suspect was homosexual/gay"},
    {value: "2008", label: "In possession of a Ballistic vest"},
    {value: "2009", label: "Suspect was Inmate/Incarcerated"},
    {value: "2010", label: "Suspect was Jailer/Police Officer"},
    {value: "2011", label: "Vendor (street or sidewalk)"},
    {value: "2012", label: "Suspect was costumed character (e.g., Barney, Darth Vader, Spiderman, etc.)"},
    {value: "2013", label: "Tour Bus/Van Operator"},
    {value: "2014", label: "Suspect was Uber/Lyft driver"},
    {value: "2015", label: "Suspect was Foster child"},
    {value: "2016", label: "Suspect was Train Operator"},
    {value: "2017", label: "Suspect was MTA Bus Driver"},
    {value: "2018", label: "Cannabis related"},
    {value: "2019", label: "Theft of animal (non-livestock)"},
    {value: "2020", label: "Mistreatment of animal"},
    {value: "2021", label: "Suspect was Aged (60+over)"},
    {value: "2022", label: "Suspect was Hitchhiker"},
    {value: "2023", label: "Suspect was Prostitute"},
    {value: "2024", label: "Suspect was Juvenile"},
    {value: "2025", label: "Suspect was Bisexual"},
    {value: "2026", label: "Suspect was Deaf/hearing impaired"},
    {value: "2027", label: "Suspect was Pregnant"},
    {value: "2028", label: "Suspect was Repeat/known shoplifter"},
    {value: "2029", label: "Victim used profanity"},
    {value: "2030", label: "Victim used racial slurs"},
    {value: "2031", label: "Victim used hate-related language"},
    {value: "2032", label: "Victim left property unattended"},
    {value: "2033", label: "Victim refused to cooperate w/investigation"},
    {value: "2034", label: "Victim was asleep/unconscious"},
    {value: "2035", label: "Racial slurs"},
    {value: "2036", label: "Hate-related language"},
    {value: "2037", label: "Temporary/Vacation rental (AirBnB, etc)"},
    {value: "2038", label: "Restraining order in place between suspect and victim"},
    {value: "2039", label: "Victim was costumed character (e.g., Barney, Darth Vader, Spiderman, etc.)"},
    {value: "2040", label: "Threats via Social Media"},
    {value: "2041", label: "Harassment via Social Media"},
    {value: "2042", label: "Victim staying at short-term vacation rental"},
    {value: "2043", label: "Victim is owner of short-term vacation rental"},
    {value: "2044", label: "Suspect staying at short-term vacation rental"},
    {value: "2045", label: "Suspect is owner of short-term vacation rental"},
    {value: "2046", label: "Suspect damaged property equal to or exceeding $25,000"},
    {value: "2047", label: "Victim was injured requiring transportation away from scene for medical reasons"},
    {value: "2048", label: "Victim was on transit platform"},
    {value: "2049", label: "Victim was passenger on bus"},
    {value: "2050", label: "Victim was passenger on train"},
    {value: "2051", label: "Suspect was passenger on bus"},
    {value: "2052", label: "Suspect was passenger on train"},
    {value: "9999", label: "Indistinctive MO"},
    {value: "2100", label: "Observation/Surveillance"},
    {value: "2101", label: "Counter Surveillance efforts"},
    {value: "2102", label: "Questions about-security procedures"},
    {value: "2103", label: "Appears to take measurements"},
    {value: "2104", label: "Photography (pics or video footage)"},
    {value: "2105", label: "Draws diagrams or takes notes"},
    {value: "2106", label: "Abandons suspicious package/item"},
    {value: "2107", label: "Abandons vehicle restricted area"},
    {value: "2108", label: "Enters restricted area w/o authorization"},
    {value: "2109", label: "Testing or Probing of Security"},
    {value: "2110", label: "Contraband at security check point"},
    {value: "2111", label: "Susp purchase of legal materials"},
    {value: "2112", label: "Acquires restricted items/information"},
    {value: "2113", label: "Acquires illegal explosive/precur agents"},
    {value: "2114", label: "Acquires illegal chemical agent"},
    {value: "2115", label: "Acquires illegal biological agents"},
    {value: "2116", label: "Acquires illegal rediological material"},
    {value: "2117", label: "Uses explosives for illegal purposes"},
    {value: "2118", label: "Uses chemical agent illegally"},
    {value: "2119", label: "Uses biological agent illegally"},
    {value: "2120", label: "Uses radiological material illegally"},
    {value: "2121", label: "Acquires uniforms without legit reason"},
    {value: "2122", label: "Acquires official vehicle without legit reason"},
    {value: "2123", label: "Pursues training/education with suspect motives"},
    {value: "2124", label: "Large unexplained sum of currency"},
    {value: "2125", label: "Multiple passports/ID's/travel documents"},
    {value: "2126", label: "Expressed or Implied threats"},
    {value: "2127", label: "Brags about affiliation with extremist organization"},
    {value: "2128", label: "Coded conversation or transmission"},
    {value: "2129", label: "Overt support of terrorist network"},
    {value: "2130", label: "Uses Facsimile/Hoax explosive device (susp offer/solicts)"},
    {value: "2131", label: "Uses Facsimile/Hoax dispersal device (susp offer/solicts)"},
    {value: "2135", label: "Sensitive event schedules(susp offer/solicts)"},
    {value: "2136", label: "VIP appearance or travel schedules (susp offer/solicts)"},
    {value: "2137", label: "Security schedules (susp offer/solicts)"},
    {value: "2138", label: "Blueprints/building plans (susp offer/solicts)"},
    {value: "2139", label: "Evacuation or emergency plans (susp offer/solicts)"},
    {value: "2140", label: "Security plans (susp offer/solicts)"},
    {value: "2141", label: "Weapons or ammunition (susp offer/solicts)"},
    {value: "2142", label: "Explosive materials(susp offer/solicts)"},
    {value: "2143", label: "Illicit chemical agents (susp offer/solicts)"},
    {value: "2144", label: "Illicit biological agents (susp offer/solicts)"},
    {value: "2145", label: "Illicit radiological material (susp offer/solicts)"},
    {value: "2146", label: "Other sensitive materials (susp offer/solicts)"},
    {value: "2150", label: "Coded/ciphered literature/correspondence"},
    {value: "2151", label: "Sensitive event schedules (susp in possession)"},
    {value: "2152", label: "VIP appearance or travel schedules (susp in possession)"},
    {value: "2153", label: "Security schedules (susp in possession)"},
    {value: "2154", label: "Blueprints/building plans (susp in possession)"},
    {value: "2155", label: "Evacuation or emergency plans (susp in possession)"},
    {value: "2156", label: "Security plans (susp in possession)"},
    {value: "2157", label: "Weapons or ammunition (susp in possession)"},
    {value: "2158", label: "Explosive materials (susp in possession)"},
    {value: "2159", label: "Illicit chemical agents (susp in possession)"},
    {value: "2160", label: "Illicit biological agents (susp in possession)"},
    {value: "2161", label: "Illicit radiological material (susp in possession)"},
    {value: "2162", label: "Other sensitive materials (susp in possession)"},
    {value: "2163", label: "Facsimile/Hoax explosive device (susp in possession)"},
    {value: "2164", label: "Facsimile/Hoax dispersal device (susp in possession)"},
    {value: "2170", label: "Associates with known/susp terrorist"},
    {value: "2171", label: "Corresponds w/suspected terrorist"},
    {value: "2172", label: "In photos w/suspected terrorists"},
    {value: "2173", label: "Organization supports overthrow/violent acts"},
    {value: "2180", label: "Bomb/explosive device"},
    {value: "2181", label: "Biological agent"},
    {value: "2182", label: "Chemical agent"},
    {value: "2183", label: "Radiological matter"},
    {value: "2184", label: "Military ordinance"},
    {value: "2185", label: "Incendiary device"},
    {value: "2186", label: "Pyrotechnics"},
    {value: "2187", label: "Facsimile/Hoax device"},
    {value: "2190", label: "Financing terrorism"},
    {value: "2191", label: "Victim's religion"},
    {value: "2192", label: "Victim's national origin"},
    {value: "2193", label: "Influencing societal action"},
    {value: "2194", label: "Furthering objectives by force"},
    {value: "2197", label: "SSI - Food/Agriculture"},
    {value: "2198", label: "Pipeline"},
    {value: "2199", label: "SSI - Postal/Shipping/Mailbox"},
    {value: "2200", label: "SSI - Government Facilities/Bldg."},
    {value: "2201", label: "Church"},
    {value: "2202", label: "Synagogue"},
    {value: "2203", label: "University"},
    {value: "2204", label: "School"},
    {value: "2205", label: "Sports Venue"},
    {value: "2206", label: "Theater"},
    {value: "2207", label: "Amusement Park"},
    {value: "2208", label: "Shopping Mall"},
    {value: "2209", label: "Convention Center"},
    {value: "2210", label: "Mass Gathering Location"},
    {value: "2211", label: "Bridge"},
    {value: "2212", label: "High-Rise Building"},
    {value: "2213", label: "Airport"},
    {value: "2214", label: "Freight Train"},
    {value: "2215", label: "Train Tracks"},
    {value: "2216", label: "SSI - Chemical storage/Manufacturing plant"},
    {value: "2217", label: "SSI - Telecommunication Facility/Location"},
    {value: "2218", label: "SSI - Energy Plant/Facility"},
    {value: "2219", label: "SSI - Water Facility"},
    {value: "2220", label: "Sewage Facility/Pipe"},
    {value: "2221", label: "SSI - Nuclear Facility, Reactors, Materials & Waste"},
    {value: "2222", label: "SSI - Dam/Reservoir"},
    {value: "2223", label: "SSI - National Monuments/Icon/Cultural significance"},
    {value: "2224", label: "Tactical significance"},
    {value: "2225", label: "SSI - Healthcare & Public Health/Hospital/Medical Clinic"},
    {value: "2226", label: "Abortion clinic"},
    {value: "2227", label: "SSI - Defense Industrial Base/Facility"},
    {value: "2228", label: "SSI - Transportation System"},
    {value: "2229", label: "SSI - Commercial Facilities"},
    {value: "2230", label: "SSI - Information Technology"},
    {value: "2231", label: "SSI - Banking and Finance"},
    {value: "2232", label: "SSI - Critical Manufacturing"},
    {value: "2233", label: "SSI - Emergency Services"},
    {value: "2234", label: "SSI - Waste"},
    {value: "2301", label: "Breach/Attempted Intrusion"},
    {value: "2302", label: "Misrepresentation"},
    {value: "2303", label: "Theft/Loss/Diversion"},
    {value: "2304", label: "Sabotage/Tampering/Vandalism"},
    {value: "2305", label: "Cyber Attack"},
    {value: "2306", label: "Espouses violent extremist views"},
    {value: "2307", label: "Aviation activity"},
    {value: "2308", label: "Eliciting information"},
    {value: "2309", label: "Recruiting"},
    {value: "2310", label: "Materials"},
    {value: "2311", label: "Acquisition of expertise"},
    {value: "2312", label: "Weapons discovery"},
    {value: "2313", label: "Finance"},
    {value: "2314", label: "TSC hit"},
    {value: "2315", label: "Sector-Specific Incident (SSI)"},
    {value: "3001", label: "T/C - Veh vs Non-collision"},
    {value: "3002", label: "T/C - Officer Involved T/C"},
    {value: "3003", label: "T/C - Veh vs Ped"},
    {value: "3004", label: "T/C - Veh vs Veh"},
    {value: "3005", label: "T/C - Veh vs Veh on other roadway"},
    {value: "3006", label: "T/C - Veh vs Parked Veh"},
    {value: "3007", label: "T/C - Veh vs Train"},
    {value: "3008", label: "T/C - Veh vs Bike"},
    {value: "3009", label: "T/C - Veh vs M/C"},
    {value: "3010", label: "T/C - Veh vs Animal"},
    {value: "3011", label: "T/C - Veh vs Fixed Object"},
    {value: "3012", label: "T/C - Veh vs Other Object"},
    {value: "3013", label: "T/C - M/C vs Veh"},
    {value: "3014", label: "T/C - M/C vs Fixed Object"},
    {value: "3015", label: "T/C - M/C vs Other"},
    {value: "3016", label: "T/C - Bike vs Veh"},
    {value: "3017", label: "T/C - Bike vs Train"},
    {value: "3018", label: "T/C - Bike vs Other"},
    {value: "3019", label: "T/C - Train vs Veh"},
    {value: "3020", label: "T/C - Train vs Train"},
    {value: "3021", label: "T/C - Train vs Bike"},
    {value: "3022", label: "T/C - Train vs Ped"},
    {value: "3023", label: "T/C - Train vs Fixed Object"},
    {value: "3024", label: "T/C - (A) Severe Injury"},
    {value: "3025", label: "T/C - (B) Visible Injury"},
    {value: "3026", label: "T/C - (C) Complaint of Injury"},
    {value: "3027", label: "T/C - (K) Fatal Injury"},
    {value: "3028", label: "T/C - (N) Non Injury"},
    {value: "3029", label: "T/C - Hit and Run Fel"},
    {value: "3030", label: "T/C - Hit and Run Misd"},
    {value: "3032", label: "T/C - Private Property - Yes"},
    {value: "3033", label: "T/C - Private Property - No"},
    {value: "3034", label: "T/C - City Property Involved - Yes"},
    {value: "3035", label: "T/C - City Property Involved - No"},
    {value: "3036", label: "T/C - At Intersection - Yes"},
    {value: "3037", label: "T/C - At Intersection - No"},
    {value: "3038", label: "T/C - DUI Felony"},
    {value: "3039", label: "T/C - DUI Misdemeanor"},
    {value: "3040", label: "T/C - Resulting from Street Racing/Speed Exhibition"},
    {value: "3062", label: "T/C - Bicyclist in Bicycle Lane"},
    {value: "3101", label: "T/C - PCF (A) In the Narrative"},
    {value: "3102", label: "T/C - PCF (B) Other Improper Driving"},
    {value: "3103", label: "T/C - PCF (C) Other Than Driver"},
    {value: "3104", label: "T/C - PCF (D) Unk"},
    {value: "3201", label: "T/C - Weather/Lighting/Roadway"},
    {value: "3301", label: "T/C - Traffic Control Devices"},
    {value: "3401", label: "T/C - Type of Collision"},
    {value: "3501", label: "T/C - Ped Actions"},
    {value: "3601", label: "T/C - Special Information and Other"},
    {value: "3602", label: "T/C - Unlicensed motorist"},
    {value: "3603", label: "T/C - Bicyclists colliding into opened vehicle door"},
    {value: "3701", label: "T/C - Movement Preceding Collision"},
    {value: "3801", label: "T/C - Sobriety"},
    {value: "3901", label: "T/C - Safety Equipment"},
    {value: "4001", label: "T/C - Central"},
    {value: "4002", label: "T/C - Rampart"},
    {value: "4003", label: "T/C - Southwest"},
    {value: "4004", label: "T/C - Hollenbeck"},
    {value: "4005", label: "T/C - Harbor"},
    {value: "4006", label: "T/C- Hollywood"},
    {value: "4007", label: "T/C - Wilshire"},
    {value: "4008", label: "T/C - West Los Angeles"},
    {value: "4009", label: "T/C - Van Nuys"},
    {value: "4010", label: "T/C - West Valley"},
    {value: "4011", label: "T/C - Northeast"},
    {value: "4012", label: "T/C - 77th"},
    {value: "4013", label: "T/C - Newton"},
    {value: "4014", label: "T/C - Pacific"},
    {value: "4015", label: "T/C - North Hollywood"},
    {value: "4016", label: "T/C - Foothill"},
    {value: "4017", label: "T/C - Devonshire"},
    {value: "4018", label: "T/C - Southeast"},
    {value: "4019", label: "T/C - Mission"},
    {value: "4020", label: "T/C - Olympic"},
    {value: "4021", label: "T/C - Topanga"},
    {value: "4024", label: "T/C - Central Traffic (CTD)"},
    {value: "4025", label: "T/C - South Traffic (STD)"},
    {value: "4026", label: "T/C - Valley Traffic (VTD)"},
    {value: "4027", label: "T/C - West Traffic (WTD)"},
    ]
  useEffect(() => {
    Papa.parse(
      "/data/Traffic_Collision_Data_from_2010_to_Present_20240319.csv",
      {
        download: true,
        header: true,
        complete: (result) => {
          setData(result.data);
        },
      }
    );
  }, []);
  return (
    <>
      <Map data={data} options={options}/>
    </>
  );
}
